<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DeviceMetrics.fs" />
    <Compile Include="NetworkMetrics.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pryde.Core\Pryde.Core.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
    <PackageReference Include="System.Management" Version="10.0.10" />
  </ItemGroup>

</Project>
